services:
  app:
    environment:
      - OPENAI_API_KEY=${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}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"

    restart: on-failure