name: Trigger auto deployment for civicflowdemostrador2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/civicflowdemostrador2-AutoDeployTrigger-80e81cdc-7462-4ac2-babb-0d38d619f17b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CIVICFLOWDEMOSTRADOR2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CIVICFLOWDEMOSTRADOR2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CIVICFLOWDEMOSTRADOR2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: civicflowcr.azurecr.io
          registryUsername: ${{ secrets.CIVICFLOWDEMOSTRADOR2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CIVICFLOWDEMOSTRADOR2_REGISTRY_PASSWORD }}
          containerAppName: civicflowdemostrador2
          resourceGroup: Demostradores-civicflow
          imageToBuild: civicflowcr.azurecr.io/civicflowdemostrador2:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


